// apps/web/src/pages/sales/InvoiceDetailPage.tsx
// ════════════════════════════════════════════════════════════════════
// Invoice Detail — /sales/invoices/:id
//
// Rendered inside <ReportViewer /> so it inherits the Route Sheet /
// Gate Pass print UX: print button in the viewer chrome, @media print
// handled globally in index.css, A4-sized canvas with shadow.
//
// A4 layout (single page, 794px wide):
//   ├─ Header strip: company name + GSTIN + address · "TAX INVOICE"
//   │                · invoice no. · date · due date
//   ├─ Bill-to block: customer name / code / address / GSTIN / route
//   ├─ Line items table:
//   │   Sl | Product | HSN | Qty | Pack | Rate | Basic
//   │      | CGST% | CGST ₹ | SGST% | SGST ₹ | Total
//   ├─ Totals block + amount-in-words
//   └─ Signature area
//
// The PDF already exists in R2 (generated by the worker). If
// `invoice.pdfUrl` is set we show a "Download PDF" button that opens
// the R2-hosted file in a new tab — useful when staff want the
// original worker-generated PDF. The rendered page itself is the
// live-data A4 view for on-screen review and browser printing.
// ════════════════════════════════════════════════════════════════════

import { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import PageHeader from "@/components/PageHeader";
import { ReportViewer } from "@/components/ReportViewer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ArrowLeft, Download, FileText } from "lucide-react";
import { fetchInvoiceById } from "@/services/api";

// ── Formatters ────────────────────────────────────────────────
const fmtMoney = (n: number | string) =>
  new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(typeof n === "string" ? parseFloat(n) || 0 : n);

const fmtDate = (iso: string | null) => {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-IN", {
    day:   "2-digit",
    month: "short",
    year:  "numeric",
  });
};

// ── Company info ──────────────────────────────────────────────
// Hardcoded to match the seed values in 0001_initial_schema.sql
// (system_settings.organization.*). When the Settings page is wired
// to a real /settings endpoint, swap this to useQuery(['settings']).
const COMPANY = {
  name:    "Haveri District Co-operative Milk Producers' Union Ltd",
  gstin:   "29AABCH1234F1Z5",
  address: "Main Road, Haveri, Karnataka - 581110",
  phone:   "+91 8382 123456",
  email:   "admin@haverimunion.coop",
};

// ════════════════════════════════════════════════════════════════════
// Number → Indian amount in words
// ════════════════════════════════════════════════════════════════════
// Standard on GST tax invoices in India. Handles lakhs/crores grouping.
function amountInWords(n: number): string {
  if (!isFinite(n) || n < 0) return "Zero";
  const rupees = Math.floor(n);
  const paise  = Math.round((n - rupees) * 100);

  const rupeesPart = rupees === 0 ? "Zero" : numToWordsIN(rupees);
  const paisePart  = paise > 0 ? ` and ${numToWordsIN(paise)} Paise` : "";
  return `${rupeesPart} Rupees${paisePart} Only`;
}

const UNITS = [
  "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
  "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen",
  "Sixteen", "Seventeen", "Eighteen", "Nineteen",
];
const TENS = [
  "", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety",
];

function numToWordsIN(n: number): string {
  if (n === 0) return "Zero";
  const below100 = (x: number): string => {
    if (x < 20) return UNITS[x];
    const t = Math.floor(x / 10);
    const u = x % 10;
    return TENS[t] + (u ? " " + UNITS[u] : "");
  };
  const below1000 = (x: number): string => {
    const h = Math.floor(x / 100);
    const rest = x % 100;
    return (h ? UNITS[h] + " Hundred" + (rest ? " " : "") : "") + (rest ? below100(rest) : "");
  };

  // Indian grouping: crore > lakh > thousand > hundred
  const parts: string[] = [];
  const crore    = Math.floor(n / 10000000);
  n = n % 10000000;
  const lakh     = Math.floor(n / 100000);
  n = n % 100000;
  const thousand = Math.floor(n / 1000);
  n = n % 1000;

  if (crore)    parts.push(numToWordsIN(crore)    + " Crore");
  if (lakh)     parts.push(numToWordsIN(lakh)     + " Lakh");
  if (thousand) parts.push(numToWordsIN(thousand) + " Thousand");
  if (n)        parts.push(below1000(n));
  return parts.join(" ");
}

// ════════════════════════════════════════════════════════════════════

export default function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const { data, isLoading, error } = useQuery({
    queryKey: ["invoice", id],
    queryFn: () => fetchInvoiceById(id!),
    enabled: Boolean(id),
  });

  const page = useMemo(() => {
    if (!data) return null;
    return renderInvoicePage(data);
  }, [data]);

  return (
    <div>
      <PageHeader
        title="Invoice"
        description={data ? `${data.invoice.invoiceNumber}` : "Loading…"}
      >
        <Button
          variant="outline"
          size="sm"
          onClick={() => navigate("/sales/invoices")}
        >
          <ArrowLeft className="h-4 w-4 mr-1.5" />
          Back
        </Button>
        {data?.invoice.pdfUrl && (
          <Button variant="outline" size="sm" asChild>
            <a
              href={data.invoice.pdfUrl}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Download className="h-4 w-4 mr-1.5" />
              PDF
            </a>
          </Button>
        )}
      </PageHeader>

      {isLoading ? (
        <Skeleton className="h-[600px] w-full rounded-lg" />
      ) : error || !data || !page ? (
        <Card>
          <CardContent className="p-10 text-center space-y-2">
            <FileText className="h-10 w-10 mx-auto text-muted-foreground/50" />
            <p className="text-sm text-muted-foreground">
              {(error as any)?.message ?? "Invoice not found"}
            </p>
          </CardContent>
        </Card>
      ) : (
        <ReportViewer title="Tax Invoice" pages={[page]} />
      )}
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════
// A4 page renderer — inside ReportViewer
// ══════════════════════════════════════════════════════════════════
function renderInvoicePage(data: Awaited<ReturnType<typeof fetchInvoiceById>>) {
  const { invoice, items, payments } = data;

  // Addresses — prefer live dealer address, fall back to snapshot.
  const dealerAddress = [
    invoice.dealerAddress,
    invoice.dealerCity,
    invoice.dealerState,
    invoice.dealerPincode,
  ]
    .filter(Boolean)
    .join(", ") ||
    invoice.dealerAddressSnapshot ||
    "—";

  const grandTotalNum = Number(invoice.totalAmount) || 0;

  return (
    <div className="text-[11px] leading-relaxed text-black">
      {/* ── Header strip ── */}
      <div className="border-b-2 border-black pb-2 mb-3">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <h1 className="text-base font-bold uppercase tracking-wide">
              {COMPANY.name}
            </h1>
            <div className="text-[10px] mt-0.5">
              {COMPANY.address}
            </div>
            <div className="text-[10px] mt-0.5">
              Phone: {COMPANY.phone} &nbsp;·&nbsp; Email: {COMPANY.email}
            </div>
            <div className="text-[10px] mt-0.5">
              <strong>GSTIN:</strong> {COMPANY.gstin}
            </div>
          </div>
          <div className="text-right">
            <div className="text-sm font-bold uppercase tracking-widest">
              Tax Invoice
            </div>
            <div className="text-[10px] mt-0.5 text-muted-foreground">
              (ORIGINAL FOR RECIPIENT)
            </div>
          </div>
        </div>
      </div>

      {/* ── Invoice meta + Bill-to ── */}
      <div className="grid grid-cols-2 gap-4 mb-3">
        <div className="border rounded-sm p-2">
          <div className="text-[9px] uppercase tracking-wide text-muted-foreground font-semibold mb-1">
            Bill To
          </div>
          <div className="font-semibold text-[12px]">
            {invoice.dealerName}
            {invoice.dealerCode && (
              <span className="text-[10px] font-normal ml-1.5">
                ({invoice.dealerCode})
              </span>
            )}
          </div>
          <div className="text-[10px] mt-1">{dealerAddress}</div>
          {invoice.dealerPhone && (
            <div className="text-[10px] mt-0.5">
              Phone: {invoice.dealerPhone}
            </div>
          )}
          <div className="text-[10px] mt-0.5">
            <strong>GSTIN:</strong> {invoice.dealerGstNumber ?? invoice.dealerCurrentGst ?? "—"}
          </div>
          {invoice.routeName && (
            <div className="text-[10px] mt-0.5">
              <strong>Route:</strong> {invoice.routeCode} — {invoice.routeName}
            </div>
          )}
        </div>

        <div className="border rounded-sm p-2">
          <div className="text-[9px] uppercase tracking-wide text-muted-foreground font-semibold mb-1">
            Invoice Details
          </div>
          <table className="w-full text-[10px]">
            <tbody>
              <tr>
                <td className="py-0.5 pr-2 font-medium w-[45%]">Invoice No.</td>
                <td className="py-0.5 font-mono">{invoice.invoiceNumber}</td>
              </tr>
              <tr>
                <td className="py-0.5 pr-2 font-medium">Invoice Date</td>
                <td className="py-0.5">{fmtDate(invoice.invoiceDate)}</td>
              </tr>
              <tr>
                <td className="py-0.5 pr-2 font-medium">Due Date</td>
                <td className="py-0.5">{fmtDate(invoice.dueDate)}</td>
              </tr>
              <tr>
                <td className="py-0.5 pr-2 font-medium">Payment Mode</td>
                <td className="py-0.5 capitalize">
                  {invoice.paymentMode ?? "—"}
                </td>
              </tr>
              <tr>
                <td className="py-0.5 pr-2 font-medium">Payment Status</td>
                <td className="py-0.5 capitalize font-semibold">
                  {invoice.paymentStatus}
                  {invoice.paymentStatus === "partial" && (
                    <span className="font-normal text-[9px] ml-1">
                      (paid ₹{fmtMoney(invoice.paidAmount)})
                    </span>
                  )}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Line items table ── */}
      <table className="w-full text-[10px] border-collapse border border-black">
        <thead>
          <tr className="bg-muted/40 font-semibold">
            <th className="border border-black py-1 px-1 w-8 text-center">Sl</th>
            <th className="border border-black py-1 px-1 text-left">Product</th>
            <th className="border border-black py-1 px-1 w-14 text-center">HSN</th>
            <th className="border border-black py-1 px-1 w-12 text-right">Qty</th>
            <th className="border border-black py-1 px-1 w-14 text-left">Pack</th>
            <th className="border border-black py-1 px-1 w-16 text-right">Rate</th>
            <th className="border border-black py-1 px-1 w-20 text-right">Basic</th>
            <th className="border border-black py-1 px-1 w-12 text-right">CGST%</th>
            <th className="border border-black py-1 px-1 w-16 text-right">CGST ₹</th>
            <th className="border border-black py-1 px-1 w-12 text-right">SGST%</th>
            <th className="border border-black py-1 px-1 w-16 text-right">SGST ₹</th>
            <th className="border border-black py-1 px-1 w-20 text-right">Total</th>
          </tr>
        </thead>
        <tbody>
          {items.map((it, idx) => (
            <tr key={idx}>
              <td className="border border-black py-0.5 px-1 text-center">
                {idx + 1}
              </td>
              <td className="border border-black py-0.5 px-1">{it.productName}</td>
              <td className="border border-black py-0.5 px-1 text-center font-mono">
                {it.hsnNo || "—"}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {it.quantity}
              </td>
              <td className="border border-black py-0.5 px-1 text-xs">
                {it.packSize || "—"}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {fmtMoney(it.unitPrice)}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {fmtMoney(it.basic)}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {it.cgstPercent}%
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {fmtMoney(it.cgstAmount)}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {it.sgstPercent}%
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono">
                {fmtMoney(it.sgstAmount)}
              </td>
              <td className="border border-black py-0.5 px-1 text-right font-mono font-semibold">
                {fmtMoney(it.lineTotal)}
              </td>
            </tr>
          ))}
          {/* Totals row */}
          <tr className="font-bold bg-muted/30">
            <td
              colSpan={6}
              className="border border-black py-1 px-1 text-right"
            >
              TOTAL
            </td>
            <td className="border border-black py-1 px-1 text-right font-mono">
              {fmtMoney(invoice.taxableAmount)}
            </td>
            <td className="border border-black py-1 px-1" />
            <td className="border border-black py-1 px-1 text-right font-mono">
              {fmtMoney(invoice.cgst)}
            </td>
            <td className="border border-black py-1 px-1" />
            <td className="border border-black py-1 px-1 text-right font-mono">
              {fmtMoney(invoice.sgst)}
            </td>
            <td className="border border-black py-1 px-1 text-right font-mono">
              {fmtMoney(invoice.totalAmount)}
            </td>
          </tr>
        </tbody>
      </table>

      {/* ── Totals + Amount-in-words + Signature ── */}
      <div className="grid grid-cols-2 gap-4 mt-3">
        <div className="border rounded-sm p-2">
          <div className="text-[9px] uppercase tracking-wide text-muted-foreground font-semibold mb-1">
            Amount in Words
          </div>
          <div className="text-[11px] font-medium italic">
            {amountInWords(grandTotalNum)}
          </div>

          {payments.length > 0 && (
            <>
              <div className="text-[9px] uppercase tracking-wide text-muted-foreground font-semibold mt-3 mb-1">
                Payment History
              </div>
              <table className="w-full text-[9px]">
                <tbody>
                  {payments.map(p => (
                    <tr key={p.id}>
                      <td className="py-0.5 pr-2">{fmtDate(p.receivedDate)}</td>
                      <td className="py-0.5 pr-2 capitalize">{p.mode}</td>
                      <td className="py-0.5 pr-2 text-muted-foreground">
                        {p.reference ?? "—"}
                      </td>
                      <td className="py-0.5 text-right font-mono">
                        ₹{fmtMoney(p.amount)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          )}
        </div>

        <div>
          <table className="w-full text-[11px] border-collapse border border-black">
            <tbody>
              <tr>
                <td className="border border-black py-1 px-2 font-medium">
                  Taxable Amount
                </td>
                <td className="border border-black py-1 px-2 text-right font-mono">
                  ₹{fmtMoney(invoice.taxableAmount)}
                </td>
              </tr>
              <tr>
                <td className="border border-black py-1 px-2 font-medium">
                  CGST
                </td>
                <td className="border border-black py-1 px-2 text-right font-mono">
                  ₹{fmtMoney(invoice.cgst)}
                </td>
              </tr>
              <tr>
                <td className="border border-black py-1 px-2 font-medium">
                  SGST
                </td>
                <td className="border border-black py-1 px-2 text-right font-mono">
                  ₹{fmtMoney(invoice.sgst)}
                </td>
              </tr>
              <tr>
                <td className="border border-black py-1 px-2 font-medium">
                  Total Tax
                </td>
                <td className="border border-black py-1 px-2 text-right font-mono">
                  ₹{fmtMoney(invoice.totalTax)}
                </td>
              </tr>
              <tr className="bg-muted/30 font-bold">
                <td className="border border-black py-1 px-2">Grand Total</td>
                <td className="border border-black py-1 px-2 text-right font-mono">
                  ₹{fmtMoney(invoice.totalAmount)}
                </td>
              </tr>
              {Number(invoice.paidAmount) > 0 && (
                <>
                  <tr>
                    <td className="border border-black py-1 px-2 font-medium">
                      Amount Paid
                    </td>
                    <td className="border border-black py-1 px-2 text-right font-mono text-emerald-700">
                      ₹{fmtMoney(invoice.paidAmount)}
                    </td>
                  </tr>
                  <tr>
                    <td className="border border-black py-1 px-2 font-medium">
                      Balance Due
                    </td>
                    <td className="border border-black py-1 px-2 text-right font-mono font-semibold">
                      ₹{fmtMoney(
                        Number(invoice.totalAmount) - Number(invoice.paidAmount)
                      )}
                    </td>
                  </tr>
                </>
              )}
            </tbody>
          </table>

          <div className="mt-6 text-right">
            <div className="text-[10px] text-muted-foreground mb-8">
              For {COMPANY.name}
            </div>
            <div className="border-t border-black pt-1 inline-block min-w-[180px]">
              <div className="text-[10px]">Authorized Signatory</div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="mt-4 pt-2 border-t text-center text-[9px] text-muted-foreground">
        This is a computer-generated tax invoice.{" "}
        Subject to {COMPANY.address.split(",").pop()?.trim() ?? "Haveri"} jurisdiction.
      </div>
    </div>
  );
}